### ISSUE TITLE
Upgrade to 1.2.1

### ISSUE THREAD

**Issue by rgl** [StefanScherer/choco-packer#25]
Can you please upgrade to packer 1.2.1?

**Comment by rgl** [comment]
I've added a [pull request for upgrading to 1.2.1](https://github.com/StefanScherer/choco-packer/pull/26)

**Comment by StefanScherer** [comment]
Thanks for the PR! I've triggered a 1.2.1 release build https://ci.appveyor.com/project/StefanScherer/choco-packer/build/1.2.1.148
Should push the new choco package in a few minutes.
