### ISSUE TITLE
Wrong checksum for packer 1.2.2

### ISSUE THREAD

**Issue by rgl** [StefanScherer/choco-packer#28]
It seems that [packer 1.2.2](https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_windows_amd64.zip) has a different sha256 than the one that is in [chocolateyInstall.ps1](https://github.com/StefanScherer/choco-packer/blob/master/tools/chocolateyInstall.ps1). Can you please see whats going on? That was the reason for the package to be rejected by the [chocolatey automated test](https://gist.github.com/b2fac1bf93a2436650a9ac696667ba1c).

```
$ sha256sum.exe packer_1.2.2_windows_amd64.zip
9c066bbe463376f9e7991326ecba09672b121776a0f2566c2d8e6ef72d52106e *packer_1.2.2_windows_amd64.zip
```

Also the packer [packer_1.2.2_SHA256SUMS file](https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_SHA256SUMS) also has this checksum, so something odd happened between the time you've built the package and today.

**Comment by StefanScherer** [comment]
Seems Hashicorp has republished the zip again probably due to https://github.com/hashicorp/packer/issues/5990#comment-376633677

Redeplying with the same version is not a good thing IMHO. Let me see what I can do. 😀
