### ISSUE TITLE
Packer can't install on 32 bit systems

### ISSUE THREAD

**Issue by obilodeau** [StefanScherer/choco-packer#5]
I've tracked it down to this issue: https://github.com/chocolatey/choco/issues/836

Workaround is to replace choco's 7zip with a 32 bit version until a new chocolatey version with a fix is released.

Putting this here only for documentation purposes. You can close the ticket.

**Comment by StefanScherer** [comment]
@obilodeau Thanks for digging so deep and giving feedback to all the maintainers to fix it.
